name: Bug Report
description: バグレポート
labels: ["bug"]
assignees:
  - mimikun
body:
  - type: textarea
    attributes:
      label: 再現手順
      description: バグを再現する手順を書く
  - type: textarea
    attributes:
      label: 期待する挙動
      description: どういうふうに動いてほしかったか書く
  - type: textarea
    attributes:
      label: 実際の挙動
      description: 実際はどんなふうに動いたか書く
  - type: textarea
    attributes:
      label: 詳細な説明
      description: あれば書く
  - type: textarea
    attributes:
      label: ソフトのバージョンなど
      description: バージョンや環境など書く
